### ISSUE TITLE
Context menu right click issues

### ISSUE THREAD

**Issue by mazjohn** [vpinball/b2s-backglass#101]
When I re-register with ResisterApp  (run as admin), the context menu no longer appears when right clicking over a .VPX file.  I only see the context menu when right clicking over a .directb2s file... In the past I was always able to see the context menu whenever right clicking over a .VPX file. Has something changed in the expected behavior or is this a bug?

**Comment by JockeJarre** [comment]
Hi @mazjohn, yes you are right. It has been changed to make sure B2S does not touch the context menu of vpx and rather put it on the b2s file. Thanks for reminding me... this has to be documented...

**Comment by mazjohn** [comment]
Thanks for providing this explanation. I had thought something was wrong with my registry when the context no longer displayed. I use the context menu all the time, it’s a great feature. Do Appreciate.
