### ISSUE TITLE
Change build script to not include x86 nor x64 in the filename

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/b2s-backglass#104]
Since the b2s.server is built using VB.NET and is set to use x86 or x64 wherever needed using the same binary, it makes no sense to name the build either x86 or x64.

**Comment by JockeJarre** [comment]
@passionforpins 

This is how it looks now: [B2SServer-2.1.2-5efa3e7-Release-win](https://github.com/vpinball/b2s-backglass/actions/runs/9378845290/artifacts/1569702763)

**Comment by JockeJarre** [comment]
looks good to me!

**Comment by passionforpins** [comment]
Much better @JockeJarre and will certainly eliminate confusion for many.
