### ISSUE TITLE
DirectOutput DLLs - remove?

### ISSUE THREAD

**Issue by mjrgh** [vpinball/b2s-backglass#117]
I just noticed that the repos has copies of the DirectOutput DLLs and test programs... from 8 years ago.  I'm guessing these got copied into the repos a long time ago with the intention of distributing them with the release set, but given that they haven't been updated in a long time, I have to assume they're just old cruft at this point that's no longer used.  Maybe it would be best to delete them, to avoid any confusion?

These are under b2s-backglass/b2sbackglassserver/b2sbackglassserver/DirectOutputPlugin.

**Comment by JockeJarre** [comment]
Yes, seems like you are fully right. Will check it! thanks

**Comment by toxieainc** [comment]
Yes, back then, i made more or less a 1:1 copy of Herweh's source tree.
