### ISSUE TITLE
 B2S Table Settings Saving But WIll Not Apply

### ISSUE THREAD

**Issue by Spacegoogie** [vpinball/b2s-backglass#119]
Can anyone else confirm this?
Wiped all B2s registry files, installed  Ver. 2.5.0.310.
Noticed that my turning OFF the backglass did not take affect.
Tried it again no go.
Checked the B2sTableSettings file and settings had been stored showing the backglass was set to off.

Settings are saving but not being applied.

I have since went back to  2.1.2 and it is working again.

My post over at VPU - https://vpuniverse.com/forums/topic/10818-b2s-settings-not-sticking-saving/#comment-82948

**Comment by JockeJarre** [comment]
thanks for the bug report. It should work now in the build coming up in a minute, please confirm and close the ticket.

**Comment by Spacegoogie** [comment]
All seems good! Nice Work guys!  Thank you! Will  Close report.
