### ISSUE TITLE
B2S 2.1.2 Throws System NullReferenceException

### ISSUE THREAD

**Issue by Zappo-II** [vpinball/b2s-backglass#121]
I have (had) a properly working 1.3.1 Version installed in my VPX/Tables dir
I have VPX 10.7.3 final

After installing B2S 2.1.2 (Tried multiple times to install it seperately into its own dir, but then it wouldn't even start) to my vpx/tables dir it starts and fires up but immediately afterwards it throws this:

![B2S Error](https://github.com/user-attachments/assets/6b199481-d2de-446d-916b-85ecfe21d433)

Sorry for being german locale - Means something like "Unhandled Exception - ObjectReference not set to an Objectinstance"...

If I click on "continue" (Weiter), the dialog disappears shortly, then comes back...

In between the DOF Toys do fire and stuff but each and every time the PopUp pops back up and raises havoc with the Active Windows and stuf...

I have absolutely no Idea how to pin point the cause of this...

What might be of interest is:

- I Have a pinscape attached to my cab...
- I use DOF x86 and x64 provided by @mjrgh

![B2S Version](https://github.com/user-attachments/assets/f57e8196-7a76-4101-8029-99edaf189a3a)

If I remove all the 2.1.2 Stuff and replace my previous 1.3.1 version, everything is back to normal...

Any Advice welcome...

**Comment by Zappo-II** [comment]
...just looking around in the code it seems to me that:

- A Timer Tick Fires...
- The BackGlass is PollingData()
    - `Using regkey As RegistryKey = Registry.CurrentUser.OpenSubKey("Software\B2S", True)`
    - ...
    - `Dim gistringsData As String = GetGIStringsPollingData(regkey)`
    - ...
    - `GetThruAllGIStrings(gistringsData)`
- ...and Explodes...

`Private Function GetGIStringsPollingData(ByVal regkey As RegistryKey) As String` returns at least an empty string...

...and...

`Private Sub GetThruAllGIStrings(ByVal gistringsData As String)` 

... does quite a lot of stuff that might involve Objects that haven't been instantiated...

Any Advice / Help appreciated...

**Comment by Zappo-II** [comment]
This is my Registry...

![Screenshot (3)](https://github.com/user-attachments/assets/0bb8284d-88d5-4272-8ad0-e939d392044f)

Am I missing something there... 🤔 ...???

**Comment by Retsamikit** [comment]
It would be very helpful to get some more infos about your installation. 
Windows version. Build Version
VPinmame version and number
.net version 
etc.

Did you try to update Visual C++ and the .net framework?

**Comment by Zappo-II** [comment]
Thank You for takin' a look into this issue...(I think I'll stick to my version of non native english so more people could possibly follow the conversation)...

I thought this would be something that's more code related than configuration related, so my first thought was to post this here, but anyways, thank's for the link, I'll take a shot there too...

General Information:
- Windows 10 Pro - Last Updated last weekend...

For the rest of your desired information I have to get back to the cab...

Would you mind providing me with instructions on how to obtain those information, I must admit that I left Windows back when Vista was released and am not that familiar with things that are more recent than that... :smirk: ...

THX and cheers...

**Comment by Retsamikit** [comment]
There should be a setup.exe in your vpinmame folder. If you open it, there should be something about Version and Build number.
A Dot Net updater can be found here: 
https://dotnet.microsoft.com/en-us/download/dotnet-framework - youll find german installers also.. 
Also update DirectX.. just to be sure....  on a fresh system you need also VisualC++
https://learn.microsoft.com/de-de/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Zappo-II** [comment]
VPinMame is all 3.4.0.0...

![Screenshot 2024-09-24 231555](https://github.com/user-attachments/assets/ab060037-ae38-4812-8868-1741c23283d8)
![Screenshot 2024-09-24 231619](https://github.com/user-attachments/assets/14e2df8e-61a2-476e-9513-b82b2c6a3d75)

**Comment by Zappo-II** [comment]
Dot Net Framework 4.8.1 installed...
MS-VC++ 2015-2022 Redistributeables (x64) & (x86) 14.40.33810 installed...

![Screenshot 2024-09-24 232235](https://github.com/user-attachments/assets/dd76ee91-a1f5-4140-ba88-7f27a844ea09)

**Comment by Zappo-II** [comment]
DirectX 12 is installed...
![Screenshot 2024-09-24 232622](https://github.com/user-attachments/assets/af4d4ae9-1607-42a5-84e2-713b7e82a6f5)

**Comment by JockeJarre** [comment]
Hi here, thanks for posting an issue. But let us move the discussion to VPU or Discord. We can always come back here if needed...

**Comment by Zappo-II** [comment]
Ok, please check...

https://vpuniverse.com/forums/topic/10836-b2s-212-throws-system-nullreferenceexception/

...for further reference.

Will keep this issue open until resolved.

**Comment by Zappo-II** [comment]
I did a thorough testing session with nearly all available Relesaes of B2S
- 1.3.1 - Working
- 1.4.1 - Working
- 2.0.3 - Working
- 2.1.0 - Working
- 2.1.1 - Working
- 2.1.2 - Throws Exception...

Log story Short:
- All Releases besides 2.1.2 behaved and worked as expected...
- Only 2.1.2 throws the before mentioned exception...
- Even after having each and every previous version installed and working before...

Im my "opinion" this must be some kind of regression introduced with 2.1.2 if I am interpreting the changelog correctly, since as far as I understand there where only minor changes made since 2.1.1...

Could you possibly take a look if the code changes made from 2.1.1 to 2.1.2 some how relate to the Error Condition described here...???

THX and cheers...

**Comment by JockeJarre** [comment]
Hi, thanks for testing. The changes can easily be found here on github:

Here is the changes between [2.1.1 and 2.1.2](https://github.com/vpinball/b2s-backglass/compare/v2.1.1...v2.1.2)

Happy to close this issue...

**Comment by Zappo-II** [comment]
Thank you for pointing out the tag diff but I am not that into vb code that I had the slightest chance or ability to pinpoint the source of the problem I am facing here from that...

I would really appreciate if someone having that skill could spare some time to take a closer look in this direction...

I would guess (wildly) that anywhere in the If/Then/Else Christmas Trees inside ` Private Sub GetThruAllGIStrings(ByVal gistringsData As String)` of `formBackglass.vb` something is (obviously unexpected) not instantiated and that this circumstance is only relevant to the changes made since 2.1.1 which seem to me have mostly been done to some supporting Procedures/Functions related to the handled Objects and Collections there...

But as I would like to point out, I am not that familiar with modern VB or coding for Windows anymore and definitely not familiar enough with the code of the back glass server to dig deeper into that...

**Comment by JockeJarre** [comment]
Thanks for the report, it should work now with the 2.5.0.319 build. Please confirm and close the ticket.

**Comment by Zappo-II** [comment]
Thank you for getting into this, would love to check but can't find the release you are pointing to...

**Comment by JockeJarre** [comment]
Did you find the "build" not "release"?

**Comment by Zappo-II** [comment]
Ok, sorry for being THAT unresponsive but the good news is, I've tested `B2SServer-2.5.0.320-7842b36-Release-win.zip` and it seems to work perfectly well now with exact that table and B2S combination...
Happy to wait for the final release...
THX and Cheers...
