### ISSUE TITLE
Latest version stutters flippers and tables

### ISSUE THREAD

**Issue by JorgePedro65** [vpinball/b2s-backglass#123]
Hello.
Latest version 2.5.0.320 stutters flippers and most of tables.

When downgrading version, the problem disappears.

**Comment by JockeJarre** [comment]
Can you please check that you run as EXE. 
The setting is to be set here: https://github.com/vpinball/b2s-backglass/wiki/Settings#backglass-startmode

**Comment by JorgePedro65** [comment]
I always run as EXE.

**Comment by JockeJarre** [comment]
Ok, please give some example tables and backglass files with links. Cause I fo not see this happening here.
And maybe better to continue the discussion on VPU or discord

**Comment by JockeJarre** [comment]
When creating an issue, there is a list of things which has to be filled out before pressing "Submit new issue":

> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> *Note:* Are you sure there is a bug in the B2S Server and not anything related to configuration or other dependencies? If you are unsure please create a post on the [Virtual Pinball Chat Discord Server](https://discord.com/invite/YHcBrtT), channel `#db2s` or on [VPUniverse](https://vpuniverse.com/files/file/12024-b2s-backglass-server/) first.

"We" as in "me, myself and I", is not a commercial offering to find **your problems**. Please discuss with others (including me) first as described above.

No reaction, closing
