### ISSUE TITLE
Shaped Lights

### ISSUE THREAD

**Issue by ukexpat71** [vpinball/b2s-backglass#13]
Hi,
Is it possible to get shaped lights like in VPX?
Thanks,

**Comment by JockeJarre** [comment]
Hauntfreaks answered on [VPU](https://vpuniverse.com/files/file/12024-b2s-backglass-server/?do=findComment&comment=31346&tab=comments): 

> there are two different ways to light a backglass..... using the designers lighting (its terrible)  or image snippets (better option)  but this must be done in a photo/image editor
> if there looking to create shapes within the designer all you can make are round/oval lighting shapes..... so NO custom shapes (again the designers lighting is just bad)
> 

So unless someone willing to come with a pull-request, I see no possibility, sorry
