### ISSUE TITLE
The monitor is detected incorrectly.

### ISSUE THREAD

**Issue by Joey-2001** [vpinball/b2s-backglass#18]
I installed the latest version today and tested "B2S_ScreenResIdentifier.exe" for the first time.
My 4k monitor (Desktopversion) (3840x2160px) is always detected with the wrong values 2560x1440px.

![grafik](https://user-images.githubusercontent.com/35002625/197174893-e2502b86-843a-4a41-84a7-217a1c0d62d7.png)
![grafik](https://user-images.githubusercontent.com/35002625/197175147-43a9b907-cfc5-4a3f-8837-fc1d2ba955c1.png)

**Comment by JockeJarre** [comment]
did some research this evening. It seems .net has a bug... does not show 4K resolution correct. Will see if we find a different way...

**Comment by JockeJarre** [comment]
the issue isn't closed yet. According to messages on the net, this should be it, though I cannot test myself... have no 4K monitor... so I did a try in a separate branch and you can test if the new way of getting the screen size now works and report back.

You need to move the window on to the 4K screen and then it should change the text in the field.
Can you please also test the pre release version and compare? Maybe add a screenshot please?

**Comment by JockeJarre** [comment]
I have now the 1.4.2 Release Candidate 2 out as a [prerelease](https://github.com/vpinball/b2s-backglass/releases/tag/b2s-backglass-215c1b7)

**Comment by Joey-2001** [comment]
I tested the x86 and x64 version. But nothing has changed. Both versions show me 2560x1440px.

**Comment by JockeJarre** [comment]
We came to the conclusion that it only works when set to 100% scaling. I need to check if it can be easily extracted, to give a warning out...

**Comment by Joey-2001** [comment]
A reference to this would certainly be useful.
