### ISSUE TITLE
Feature Request: Add window punch functionality

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/b2s-backglass#28]
Make it possible to punch a hole into the B2S Forms, to let any other windows shine through. This should hopefully finally let all other issues with disappearing windows go away,

**Comment by toxieainc** [comment]
@JockeJarre So is this done with aboves commits? Thanks!

**Comment by JockeJarre** [comment]
yes, it is in this branch, though I am collecting the full 2.0.0 scope here.
The punch functionality is a separate executable "B2SWindowPunch" which is triggered through a cmd file B2SInit:

B2SBackglassServer.dll -> B2SInit.cmd -> B2SWindowPunch.exe

Will merge it today, but there are still some things to check for final release.
