### ISSUE TITLE
Issues with DMD and Hyperpin with Version 1.3.1.1

### ISSUE THREAD

**Issue by Andyapc** [vpinball/b2s-backglass#3]
Hi, I am having issues with DMD's hidden Behind Backglass since  I updated to version 1.3.1.1 of the B2S Backglass Server.
I have a two-screen set-up with the virtual DMD on the same screen as the backglass.
I recently updated the B2S Backglass Server as I was installing PinUp Player. The new version of the B2S Backglass server has added a new checkbox called “Bring BF Form to Top” When you initially set this it does it globally for all Backglasses.
The issue is that since this update larger backglass (i.e. larger file size) that take slightly longer to load are opening after the DMD and are hiding the DMD behind them.
This is happening for some Freezy DMD’s and nearly all Ultra DMD’s games
The usual settings i.e. “DMD to visible” on the B2S Backglass Server setting make no difference.
Unchecking “Bring BF Form to Top” on the B2S Backglass Server setting solves the problem when opening a table directly from Visual Pinball, but…… The BIG PROBLEM is that Unchecking “Bring BF Form to Top” now hides the DirectB2S Backglass behind the static backglass image used by my frontend Hyperpin.
I only realised this when I noticed the Backglass were now static with no animations. I pressed alt-Tab and realised that setting was actually causing the backglass to open behind the frontend image.
This was never an issue with the older version of the B2S Backglass Server, but PinUP Player requires the newer version.
I have no intention of moving away from Hyperpin as I have it all set-up for well over 700 tables.
I would actually like to solve the problem of the backglass opening after the DMD when the Backglass is larger and takes longer to load.
Is possible to add a 1 Second delay / pause in the table script just before the “DMD_Init” to allow the Backglass to load before the DMD?
That way I could leave “Bring BF Form to Top” checked for all tables.
Alternatively, is there a way to stop the backglass from opening behind the Hyperpin backglass image when “Bring BF Form to Top” is unchecked?
Any help would be appreciated as this only happens on about 15-20 tables such as Diablo and Stranger Things and is driving me nuts!

**Comment by JockeJarre** [comment]
I will make the "Form to Top" a three state setting or rather two separate (to allow better robustness for older versions). When both "Form to Back" and "Form to Top" is turned off it will work 100% as in the earlier versions.

**Comment by JockeJarre** [comment]
@Andyapc if you want to test a build before I merge the changes, please see under actions here
   https://github.com/JockeJarre/b2s-backglass/actions/runs/3077618126

We now have now three back glass states:

 "Form to Back" (I will continue this one and make sure the back glass stays in the back)
 "Standard"  (should now be as in 1.3.0.6 e.g. Form to Top unchecked)
"Form to Top"

**Comment by JockeJarre** [comment]
I have now added a working FormToBack setting which forces the background + Back glass + DMD to stay in back. I think it is usable for freezy's DMD extensions to allow all alpha-numeric displays to get visible. 

So I hope we can strike through that issue as well.

A test build can be found here: https://github.com/JockeJarre/b2s-backglass/actions/runs/3123621442   

Full release notes:

- Add additional setting FormToBack complementing FormToFront. Now three states available:
  1. "Standard" (both FormToBack and FormToFront turned off) is now as it was in 1.3.0.6. -> formDMD isn't controlled by the FormToFront/Back setting
  2. FormToFront sets the flag Form.TopMost = True -> cannot get any other window on top
  3. FormToBack, forces the forms back and ignores any try to get them come forward -> Windows stay in back. The B2S Server is not available in the taskbar anymore. (for the same reason)
- Merge some more settings in the dll version.
- Make sure LED "D" (Digit) updates from VPMame is forwarded to all plugins. thanks to rdowens11vx!
