### ISSUE TITLE
Bug: Fuzzy Matching Doesn't Seem to Work

### ISSUE THREAD

**Issue by eric-davis** [vpinball/b2s-backglass#33]
Doesn't seen to matter how I have the `DisableFuzzyMatching` setting configured (0 or 1) in the `B2STableSettings.xml` file, backglasses only load if the `.directb2s` filename is an exact match for the `.vpx` file. 

For example, `Medieval Madness Reloaded (Williams 1997)_Skitso_MOD_1.1.vpx` + `Medieval Madness Reloaded (Williams 1997)_Skitso_MOD_1.1.directb2s` loads up and works fine, but `Medieval Madness Reloaded (Williams 1997)_Skitso_MOD_1.1.vpx` + `Medieval Madness Reloaded (Williams 1997).directb2s` does not; regardless of `DisableFuzzyMatching` setting.

**Comment by JockeJarre** [comment]
Hello,

Some of these settings are only active in "EXE" mode (this is one of them), do you have "EXE" mode turned on?

With each release more of these settings are merged into both modes, but it hasn't happened to this one yet.

It is always useful to write which version of the Server you are using. In the latest release it will be easier to see in the settings window, which settings still aren't merged.

**Comment by JockeJarre** [comment]
No answer in 2 weeks, closing
