### ISSUE TITLE
Doc: Mentions of Designer download .. but nothing is found - or atleast I cant find it.

### ISSUE THREAD

**Issue by derwin12** [vpinball/b2s-backglass#34]
Is there a 1.4 of Designer?

**Comment by JockeJarre** [comment]
No, there is no 1.4.X of designer. Not much has happened since we took the last source from sourceforge.
There are builds available here as well but a little hidden: https://github.com/vpinball/b2s-backglass/releases/tag/b2s-backglass-f374e2d

**Comment by JockeJarre** [comment]
No answer
