### ISSUE TITLE
Feature Request: Add info if x86 or x64 bit binary in the settings window

### ISSUE THREAD

**Issue by gjenning** [vpinball/b2s-backglass#37]
It would be nice to have a about page that could be displayed form the b2s settings page that would contain info about the version and if it was the 32bit or 64bit version of b2s running...

**Comment by gjenning** [comment]
I think that when you show the version number of the b2s server, you could easily just add x86 or x64 on to the end of it so that a user would know which version of the b2s was running.  This comes into play if you have both the 32 and 64 bit versions installed, as I do on my cab.

**Comment by JockeJarre** [comment]
Hi, sounds like a very good idea! How did you get both 32 and 64 bit going? 
Do you have any instructions for it? Would like to try it out!

**Comment by JockeJarre** [comment]
Hello, I have added this information to the settings window. I could only test x86 right now, would you be so kind and test on your x64 installation?

**Comment by gjenning** [comment]
Ok, I did some quick testings, and both the 32 bit and 64 bit b2s show x86 in the settings window.  I confirmed this by completely uninstalling and removing all the registry settings for the 32 bit version so only 64bit was running and it still show incorrectly.

**Comment by Jwkramer61j** [comment]
I have them working under 2.0 BG Server. I did have to manually copy the B2S...dll with the correct version though to get DOF to work.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: gjenning ***@***.***> Date: 3/13/23  09:38  (GMT-05:00) To: vpinball/b2s-backglass ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [vpinball/b2s-backglass] Feature Request: Add info if x86 or x64 bit binary in the settings window (Issue #37) 
So what I did was install the each into there own directory like B2SBackglass-x86 and B2SBackglass-x64, then registered both.  The one reason I have requested having the x86 or x64 on the settings page was to have a verification of which server is running.  Thanks again for adding this... I am working with smaug on instructions and will be happy to add something to your wiki when we get it 100% flushed out.  I am still in the testing phases right now and verification is key.  I am planning on upgrading to the 2.0 release today and will let you know how it works on x64 and x86 side by side.

**Comment by JockeJarre** [comment]
> Ok, I did some quick testings, and both the 32 bit and 64 bit b2s show x86 in the settings window. I confirmed this by completely uninstalling and removing all the registry settings for the 32 bit version so only 64bit was running and it still show incorrectly.

I will double check this, I am afraid the code to check which plugins folder to use (plugins or pluginsx64) will have similar problems. We will find out soon!

**Comment by JockeJarre** [comment]
> I have them working under 2.0 BG Server. I did have to manually copy the B2S...dll with the correct version though to get DOF to work.

Hi Jwkramer61j, was a little hard to understand you, can you please elaborate?

**Comment by Jwkramer61j** [comment]
> > I have them working under 2.0 BG Server. I did have to manually copy the B2S...dll with the correct version though to get DOF to work.
> 
> Hi Jwkramer61j, was a little hard to understand you, can you please elaborate?

sorru about that - I was on my phone when I typed that.
I was just saying that I have both 32 bit & 64 bit B2S working (including DOF output). In my testing, a single .DLL file was all it takes to flip back and forth (B2SServerDirectOutputPlugin.dll) for DOF. I believe I just registered both 64 bit & 32 bit B2SServer and as far as the Backglass goes it works fine for either 32 or 64 bit.

**Comment by JockeJarre** [comment]
great news!
So I have another ticket going where I want to show if the process is 64 or 32 bit, and it seems the code does not catch it correctly though it is using precompiler statements (it always says 32 bit)
So I guess my code which SHOULD switch from using "Plugins" to "Plugins64" does not work either. Will check and come back!

**Comment by gjenning** [comment]
So in the x86 b2s server when vpx 32bit is running it uses plugins and when 64bit vpx is running it is using Plugins64, so that is working as expected, as far as I know.

**Comment by JockeJarre** [comment]
Perfect, I'll close the ticket! Thanks for the support!

**Comment by JockeJarre** [comment]
Or I will let it open a little more, maybe I will find a better way to show which kind of process it is

**Comment by JockeJarre** [comment]
Close this ticket for now. Can be reopened if needed.
