### ISSUE TITLE
Feature Request: Have way to unregister the b2s server and remove all registry entries

### ISSUE THREAD

**Issue by gjenning** [vpinball/b2s-backglass#38]
It would be nice to have a way to unregister the b2s server and remove all registry entries for it.  This would make for a clean uninstall of the b2s server.

**Comment by JockeJarre** [comment]
Has this something to do with running 64 & 32 bit B2S at the same time?

Then I would rather see a better solution to this if possible? maybe register them both somehow?
or keep the dll in 32bit and just have two different B2SBackglassServerEXE.exe
B2SBackglassServerEXE.exe and B2SBackglassServerEXE64.exe ?

**Comment by gjenning** [comment]
This is related to the fact that I was working with Smaug on trying to get his system setup for both x64 and x32 and things were not behaving as I would have figured.  I suspect a weird registry issue and wanted to do a complete uninstall and reinstall of the system.  I saw where you have some good information on de-registering in the wiki now.   I need to use that to verify some stuff and will followup on my findings.  I am currently running the 32bit and 64bit in different directories but this might not be doing what I think.

**Comment by JockeJarre** [comment]
You can create a "unreg" reg file, using dllview, that should do it.
