### ISSUE TITLE
Feature Request- rename 64 bit B2S server components with "64" in file names

### ISSUE THREAD

**Issue by passionforpins** [vpinball/b2s-backglass#40]
For example the 32 bit version name is B2SBackglassServer.dll so I suggest naming the 64 bit version B2SBackglassServer64.dll.
This will be in line with the naming convention used by other visual pinball authors from dmd driver dll's to vpx itself.
This way both versions can co-exist in the same folder

**Comment by JockeJarre** [comment]
B2S Server, which is written in VB.Net, it is already compiled as both 32 and 64 bit, so there is no need to complicate things further by having to register different files.
Similar to how Java does it... See https://en.wikipedia.org/wiki/Common_Intermediate_Language

For VPMame it is a different story as it a c/c++ solution where you have to compile to the final CPU architecture.
