### ISSUE TITLE
B2SBackglassServerRegisterApp.exe not enabling right-click options

### ISSUE THREAD

**Issue by sllerts** [vpinball/b2s-backglass#41]
I have a working setup of VPX 10.7.3 and B2S.  I updated to 2.0 and saw that there are right-click options for .vpx and related files in the readme.  I've run the B2SBackglassServerRegisterApp.exe app multiple times, even as admin, but I have no right-click options.  I've followed all instructions to the letter.

This is on a manual install of everything (I didn't use Baller Installer) in Windows 10.  Please let me know what additional info you need.

**Comment by JockeJarre** [comment]
I will check

**Comment by JockeJarre** [comment]
Hi, can you please check if the latest build solves your problem:

https://github.com/vpinball/b2s-backglass/actions/runs/4465478810

You need to start the register app again, and you should now get a second question as described in the [wiki](https://github.com/vpinball/b2s-backglass/wiki/B2SBackglassServerRegisterApp)

**Comment by JockeJarre** [comment]
Would you be so kind and test if this helps?

**Comment by JockeJarre** [comment]
No reaction after three weeks

**Comment by JockeJarre** [comment]
Ok, we can reopen in case there is an issue still
