### ISSUE TITLE
Feature request: It should be possible to control B2SWindowPunch through the settings

### ISSUE THREAD

**Issue by pacleary** [vpinball/b2s-backglass#45]
I added "B2SWindowPunch=off" to the last line of my ScreenRes.txt file, but it is being ignored. This is a problem as I use custom window frames and padding on my DMDs and it is creating extra padding around the cutout.

**Comment by JockeJarre** [comment]
Can you please copy your ScreenRes.txt here

**Comment by JockeJarre** [comment]
Hello, now I understand. 
You want to deactivate it completely? The "B2SWindowPunch=off" line only works in a tablename.res file...

If you want to turn this off completely, you can just rename the file B2SInit.cmd to something else, and it will not be called at all.

**Comment by pacleary** [comment]
That would be very helpful! In the meantime I will do your suggestion.
Thanks!

**Comment by JockeJarre** [comment]
Hello, with the latest build under actions, this can now be controlled through a registry key and also through Settings->More...
Can you please try it out and close the issue?
