### ISSUE TITLE
Feature Request - Create a way to add FullDMD backgrounds similar to how alt sound or color DMDs work.

### ISSUE THREAD

**Issue by mikeybenson** [vpinball/b2s-backglass#50]
How hard would it be to make the FullDMD part of the backglass more like the way alt music or alt color work? Where you would put an image somewhere and then you check a box to turn it on.  Adding a 3rd screen Full DMD image is trivial, but you have to load and export an entire backglass for it.

Edit: After talking to you on discord it seems like this would not be a hard transition. Much of the structure is already there through the "Background" feature in the screenres file. It seems like you could pull table info to assign the background naming convention for background paths. The background images could live in a folder within the B2Sserver. I will add what you wrote to me below.

------- jarr3 --------
You could use the Background feature for this even though it means you need a res file for each table. I have had thoughts to allow "template" strings for the file name of the background picture though. 

for example if the Background picture path would look like this:
c:\vPinball\B2SServer\Backgrounds{tablename}.png
Table name would then be replaced with your tablename before trying to load the background. Please add an issue on github https://github.com/vpinball/b2s-backglass/issues as a feature request, so that we do not forget it...
Apart from {tablename} i would add {GameName} = rom name or {manufactor} which will take the creator name from the table name.

Having a tablename "Blood Machines (VPW 2022)" 
Manufactor = VPW
Tablename = Blood Machines (VPW 2022)
GameName = bloodmach1
Name = Blood Machines
Year = 2022

These are just some examples I could think of, but maybe enough?

**Comment by JockeJarre** [comment]
yes it is good enough as a memory help for me

**Comment by JockeJarre** [comment]
I have now added a first version for this.

In **B2SBackglassServerEXE** For activated background pictures, it is possible to enter a path with placeholders for "_keys_" in the table name.

  The _keys_ are extracted using regular expressions (currently hardcoded)     
  e.g. for a table name "Blood Machines (VPW 2022) V1.21" it would extract as "{name} ({manufactor} {year}) {extra}"

So if the background picture path is entered like "c:\vPinball\B2SServer\backgrounds\Grill{manufactor}.png" in the res file, it will be replaced with "c:\vPinball\B2SServer\backgrounds\GrillVPW.png"

If no keys can be extracted from the table name, all combinations {name}, {year}... are replaced with an empty string and would become "c:\vPinball\B2SServer\backgrounds\Grill.png" in the example above.


This way only one res file is needed for many tables, but can have certain design or logos depending on the manufactor, name or even year.

**Comment by mikeybenson** [comment]
I look forward to trying it out. Thanks for working on this!
