### ISSUE TITLE
B2sServer.exe Crashes immediately

### ISSUE THREAD

**Issue by Websteria** [vpinball/b2s-backglass#51]
My backglass server was working fine and then stopped working all together except for pup packs. Would appreciate any advice that could set me on the right path.

Here are the errors from Event Log:

Application: B2SBackglassServerEXE.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(System.String, System.Globalization.NumberFormatInfo)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(System.String)

Exception Info: System.InvalidCastException
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(System.String)
   at B2S.B2SScreen.ReadB2SSettingsFromFile()
   at B2S.B2SScreen..ctor()
   at B2S.formBackglass..ctor()

Exception Info: System.InvalidOperationException
   at B2S.My.MyProject+MyForms.Create__Instance__[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   at B2S.formBackglass.Main()

and

Faulting application name: B2SBackglassServerEXE.exe, version: 2.0.2.0, time stamp: 0x642d07bd
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1555, time stamp: 0x235a45d0
Exception code: 0xe0434352
Fault offset: 0x000000000008fdec
Faulting process id: 0x0x2F58
Faulting application start time: 0x0x1D974BE7F619815
Faulting application path: D:\vPinball\VisualPinball\Tables\B2SBackglassServerEXE.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 77db2764-528e-4a3c-8435-cb59faafb17c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by JockeJarre** [comment]
Hello, could you please connect through VPU or VPForums (both Jarr3) 
I need res files and maybe some more info what tables you have used.
Could you please test with the debug build https://github.com/vpinball/b2s-backglass/actions/runs/4625460470, 
it is the exact same build but with debug information added. This to see if we get more information?

**Comment by Websteria** [comment]
The problem was multiple screenres.txt files. I have resolved it. Thank you for your help!!!!On Apr 22, 2023, at 8:11 AM, Jarr3 ***@***.***> wrote:﻿
Hello, could you please connect through VPU or VPForums (both Jarr3)
I need res files and maybe some more info what tables you have used.
Could you please test with the debug build https://github.com/vpinball/b2s-backglass/actions/runs/4625460470,
it is the exact same build but with debug information added. This to see if we get more information?

**Comment by JockeJarre** [comment]
can you still reproduce it? Please if you find the problematic file, add it here, so that I can fix the problem...

**Comment by Websteria** [comment]
I believe I had a v1 screenres somewhere that it was accessing and the format difference causes it to crash. Incidentally what is the proper format for defining backglass as x pixels over? @x,0. Just @x?On Apr 22, 2023, at 8:35 AM, Jarr3 ***@***.***> wrote:﻿
can you still reproduce it? Please if you find the problematic file, add it here, so that I can fix the problem...

**Comment by JockeJarre** [comment]
the format is 

@x or
@100
