### ISSUE TITLE
Must run RegisterDirectOutputComObject.exe as Administrator

### ISSUE THREAD

**Issue by CFTBL** [vpinball/b2s-backglass#53]
Just a minor suggestion for the 64bit VPX Pincab Setup Guide. In the 64-bit DOF setup section, where it says "Go into \DirectOutput-x86 into and run RegisterDirectOutputComObject.exe"... I'd suggest adding "(Run as Administrator)". Some people (OK, me) got tangled-up here trying to run that exe without administrator privilege.

**Comment by JockeJarre** [comment]
Thanks! Updated!
