### ISSUE TITLE
DOF post the full name so new users know

### ISSUE THREAD

**Issue by Tom-Neverwinter** [vpinball/b2s-backglass#54]
To get DOF working in the 64bit environment, you will have to download the x64 build provided here:

**Direct Open Framework**

https://www.youtube.com/watch?v=FQgRwxiUYmc

seems to be a DMX esque led controller like WLED is for us Christmas and holiday lighting people [shoutout xlights]

**Comment by JockeJarre** [comment]
Where do you see any x64 build link here?

**Comment by JockeJarre** [comment]
B2S Server, which is written in VB.Net, it is already compiled as both 32 and 64 bit, so there is no need to complicate things further by having to register different files.
Similar to how Java does it... See https://en.wikipedia.org/wiki/Common_Intermediate_Language

For VPMame it is a different story as it a c/c++ solution where you have to compile to the final CPU architecture.

No more information supplied, closing
