### ISSUE TITLE
B2S does not take some values into account for the tables when defined in the global part of the B2STableSettings.xml

### ISSUE THREAD

**Issue by M-oster** [vpinball/b2s-backglass#55]
I have stored the table-files in different directories, to sort them by categories. To allow easy configuration,  each directory contains a B2STableSettings.xml File.
My approach was to config this xml file that all tables in this directory for example display their grill
But when adding the line `<HideGrill>0</HideGrill>` in the global part of the xml file, B2S does not consider this config for the table. 
I have to config this part for each table manually.
Then I have tested the whole values for the visibility config part: some values are working, the most are not working (as global).
**working XML values:**
- the combination FormToFront/FormToBack for the config. of "Brings forms.."
- FormNoFocus for the check field "Form no Focus"

**not working XML values**
- HideGrill for "Grill"
- HideB2SDMD for "B2S DMD"
- StartBackground for "Background"

The most important values for me are HideGrill and HideB2SDMD. The other values of the other sections have not been tested

**Comment by JockeJarre** [comment]
yes, sounds like a great idea

**Comment by JockeJarre** [comment]
@M-oster, do you want to test if this works for you now?

**Comment by M-oster** [comment]
Many thanks. I have tested it and it works fine now.
The values are working now as Global and are overwritten within the table-specific section of a table.
Many thanks

**Comment by M-oster** [comment]
closed the issue
