### ISSUE TITLE
No more sound on some tables since the switch to 64 bits

### ISSUE THREAD

**Issue by Denys06** [vpinball/b2s-backglass#56]
I recently switched to Visual Pinball 64 Bits. Since then, several musics/sounds are no longer played on certain tables: **Medieval Madness**, **Monster Bash** and **Big Bang Bar**.
Do you know how to fix this problem please ?

**Comment by JockeJarre** [comment]
Hi Denys06, hmm can you please try to ask this is one of the forums out there vpforums or VPUniverse before we add an issue.
I doubt this is a in issue of the B2SServer, so I close the issue here. If we notice there is an error of B2SServer it can still be opened again.
