### ISSUE TITLE
Backglass loads in front of DMD

### ISSUE THREAD

**Issue by jkh0208** [vpinball/b2s-backglass#58]
The backglass always loads in front of the DMD on most tables, even if I bring the DMD in front, close VPX and relaunch the table.

**Comment by JockeJarre** [comment]
> The backglass always loads in front of the DMD on most tables, even if I bring the DMD in front, close VPX and relaunch the table.

Please double check your DmdDevice.ini... see the official [freezy documentation](https://github.com/freezy/dmd-extensions#output-configuration) :

[virtualdmd]
stayontop = true

Additionally, as mentioned above we have the [FormToFront/Back](https://github.com/vpinball/b2s-backglass/wiki/Settings#visibility) settings to control this in the B2SServer (for later versions) 

There is also a feature named [B2SWindowPunch](https://github.com/vpinball/b2s-backglass/wiki/B2SWindowPunch), which allow "punching holes" through the other forms.

**Comment by jkh0208** [comment]
> > The backglass always loads in front of the DMD on most tables, even if I bring the DMD in front, close VPX and relaunch the table.
> 
> Please double check your DmdDevice.ini... see the official [freezy documentation](https://github.com/freezy/dmd-extensions#output-configuration) :
> 
> [virtualdmd] stayontop = true
> 
> Additionally, as mentioned above we have the [FormToFront/Back](https://github.com/vpinball/b2s-backglass/wiki/Settings#visibility) settings to control this in the B2SServer (for later versions)
> 
> There is also a feature named [B2SWindowPunch](https://github.com/vpinball/b2s-backglass/wiki/B2SWindowPunch), which allow "punching holes" through the other forms.

These are all things I've tried.  I got DMDext to work perfectly, but the built-in DMD randomly works and most of the time doesn't.  When it doesn't, I can't even bring it forward by alt-tabbing.  The B2SWindowPunch behaves strangely for me.  It works with DMDext, except it sometimes only punches part of it so the DMD is partially obscured by the backglass.  It doesn't do anything with the built-in DMD for me.

**Comment by JockeJarre** [comment]
B2SWindowPunch waits 10 seconds, and then it punches. The windows has to be in the right position before that.

let us continue this in the forum and supply some screenshots, there more people can help.

**Comment by JockeJarre** [comment]
No more information available, if needed it can be reopened
