### ISSUE TITLE
Compile 64bit version using filenames that end in 64 so it can exist beside the 32bit

### ISSUE THREAD

**Issue by wiesshund** [vpinball/b2s-backglass#59]
Compile 64bit version using filenames that end in 64 so it can exist beside the 32bit

Or perhaps compile like FlexDMD which handles that internally depending on if it is being called by x86 or x64?

**Comment by JockeJarre** [comment]
Hi Wiess,
As always, good ideas! 
Although for B2S, which is written in VB.Net, it is already compiled as both 32 and 64 bit, so there is **no need** to complicate things further by having to register different files.  
Similar to how Java does it...   See https://en.wikipedia.org/wiki/Common_Intermediate_Language

For FlexDMD and VPMame it is a different story as they are c/c++ solutions where you **have to** compile to the final CPU architecture.

**Comment by wiesshund** [comment]
it was not working for me at all
but then i deleted the whole vpx folder since it had been through a bazillion beta changes
and now it works
I dont imagine the reason why it didnt work is remotely useful at this point..

Was weird though, it would work if i kept flipping the compiles back and forth

Oh well.
Others noting same issue should probably do same thing.

**Comment by wiesshund** [comment]
flexDMD isnt c++, freezy's is though, flex is VBnet i believe?

**Comment by JockeJarre** [comment]
yes, you are almost right it isn't c++ but C#. So it is also using the .Net virtual machine, could maybe also be compiled for both...

So, can we close this issue?

**Comment by wiesshund** [comment]
I think so?

**Comment by JockeJarre** [comment]
If we would still need this, we can always reopen it...
