### ISSUE TITLE
DMD does not display for some directB2S 2 screen / 3 screen blackglasses (B2S Server)

### ISSUE THREAD

**Issue by wiesshund** [vpinball/b2s-backglass#6]
DMD does not display for some directB2S 2 screen / 3 screen blackglasses
Dont know if it goes behind as b2s server no longer shows a separate process in the taskbar for the backglass and dmd windows
tried alt tabbing but no dice

I am putting screenres.txt here, and i am putting one of directb2s files here as well
this backglass  did work in 1.3.0 b2s server
[Tom_and_Jerry.zip](https://github.com/vpinball/b2s-backglass/files/9482360/Tom_and_Jerry.zip)

[ScreenRes.txt](https://github.com/vpinball/b2s-backglass/files/9482356/ScreenRes.txt)

I have tried re editing the backglass, deleted the DMD, recreated the DMD, tried setting it to display both only on backglass and
and display on dmd or backglass

Not sure where it goes, i tried purposely setting the backglass to 320X240
just to see if i could see the DMD below it, but no dice.

There are other backglasses like this, that have this same issue
I have no problem reading the directb2s file in notepad++, but i dont know what i would be looking for that the new b2s server does not like about it

Also, the new screenres identifier app
I found that if you put in values for the DMD, to like test a 3 screen environment on a 2 screen setup
that if you try and get rid of the DMD later, the DMD values remain in screenres.txt, even though you tried to zero them out and check that backglass is full screen

you have to delete screenres.txt and then let it create a new one
i thought it was a fluke but i tried it several times, and each time had to just delete screenres,txt and build a new one.
Not a big deal except for people that wont know to go and delete that.

**Comment by JockeJarre** [comment]
I am trying to get this to fail on my side, without success...
Which DMD is missing? The B2S DMD, VPM DMD or DLL DMD?

![image](https://user-images.githubusercontent.com/12571104/190915904-1cdbf3d3-54fb-4d68-9e6d-8a7de1a1da42.png)

**Comment by JockeJarre** [comment]
I am already working on a similar issue, can you please test if this build maybe solves it for you as well?

https://github.com/JockeJarre/b2s-backglass/actions/runs/3077618126

**Comment by wiesshund** [comment]
the B2S DMD
Not sure where it goes
it is not under the backglass, i checked for that by setting the backglass really small.
And it is set to show too.

If i mock up a new backglass, it appears fine

**Comment by wiesshund** [comment]
> I am already working on a similar issue, can you please test if this build maybe solves it for you as well?
> 
> https://github.com/JockeJarre/b2s-backglass/actions/runs/3077618126

Does it matter that it says your build failed?

**Comment by wiesshund** [comment]
tried it anyways.
this build seems to work fine
other does not

I can not see if the DMD is going behind the backglass or what it is doing
tried bastardizing screenres.txt to ensure the DMD would be someplace other than the screen space the backglass is in
but i can not see any part of it, not even sure if it is running anyplace as the dmd no longer shows as a separate form window process as it did in i think 1.3.0, or was it 1.3.1.0 ?

but the build i pulled from your fork works

**Comment by JockeJarre** [comment]
> > I am already working on a similar issue, can you please test if this build maybe solves it for you as well?
> > https://github.com/JockeJarre/b2s-backglass/actions/runs/3077618126
> 
> Does it matter that it says your build failed?

No, it was only the designer build which failed to recreate the documentation.

**Comment by JockeJarre** [comment]
> I can not see if the DMD is going behind the backglass or what it is doing tried bastardizing screenres.txt to ensure the DMD would be someplace other than the screen space the backglass is in but i can not see any part of it, not even sure if it is running anyplace as the dmd no longer shows as a separate form window process as it did in i think 1.3.0, or was it 1.3.1.0 ?
> 
> but the build i pulled from your fork works

Yes, I thought it would be good to have them joined into one. But it seems to make problem in certain places. So the DMD is now always a separate Form and can be handled separately. 

The "Standard" and "Form to Front" setting should stay as is now, and I will continue on the "Form to back" before releasing, 
"Form to back" should make the forms stay in back even if pressed on. This to allow PUP videos playing in front more stable.

**Comment by JockeJarre** [comment]
I have now added a working FormToBack setting which forces the background + Back glass + DMD to stay in back here #9
