### ISSUE TITLE
Can the embedded EM reel sound effect be removed, or made optional?

### ISSUE THREAD

**Issue by wrd1972** [vpinball/b2s-backglass#62]
I simply want to be able to turn off the EM reel sound effect when needed. The current sound is much to loud relative to the other sounds and is very distracting. Would love to have the ability to turn it off/on as an option, and if its on be able to adjust its volume.

Could it also be doable to use your own personal reel sound and not be limited to the stock one?

Thanks
Bill

**Comment by wiesshund** [comment]
I would vote for either just remove
or replace with an empty sound file

table authors can have it make noise

**Comment by JockeJarre** [comment]
I have looked into this and have come to the conclusion that it is already possible to turn off sounds per table in the directb2s files:

In this part of the directb2s, setting Sound3-5 to an empty string disables the builtin sound for reels

``` XML
  <Scores ReelCountOfIntermediates="0" ReelRollingDirection="Up" ReelRollingInterval="20">
    <Score Sound3="" Sound4="" Sound5="" Parent="Backglass" ID="1" B2SStartDigit="0" B2SScoreType="1" B2SPlayerNo="1" ReelType="ImportedEMR_T2_0" ReelIlluImageSet="1" ReelIlluLocation="3" ReelIlluIntensity="4" ReelIlluB2SID="25" ReelIlluB2SIDType="1" ReelIlluB2SValue="0" ReelLitColor="255.69.0" ReelDarkColor="15.15.15" Glow="900" Thickness="1400" Shear="10" Digits="5" Spacing="100" DisplayState="0" LocX="666" LocY="177" Width="549" Height="77" />
  </Scores>

```

I am also looking at adding a flag from the B2SServer that can be used globally by changing the B2STableSettings.xml or per table in the settings.

**Comment by JockeJarre** [comment]
I have now committed a small tool which will the add or remove the attributes muting the reel sounds.
It is a windows batch file using powershell to transform the directb2s files using xslt.

**Comment by JockeJarre** [comment]
I see this as a solution for authors of b2sdirect backglass files.
