### ISSUE TITLE
New Feature Request Backglass Hidden

### ISSUE THREAD

**Issue by Loadedweapon** [vpinball/b2s-backglass#67]
I would like to know if any way to add the feature to hide the backglass?
Example: So Back To The Future has a backglass with a nice full dmd score display that I prefer over just the pinmame or externaldmd. Also I really like the Puppack for BTTF but if I try to run both the backglass bleeds through on the videos. Would be cool if we could hide the backglass and keep the fulldmd score running. Hope that makes sense. Thanks!

**Comment by JockeJarre** [comment]
This is already possible today with a workaround; take a res file where you change the position of the backglass to point to an area outside your field of view... far right for example.

Try placing your pre-defined res files in the **B2SServer\ScreenResTemplates** folder name it something like "backglass deactivated" and then run the **B2SBackglassServerRegisterApp.exe** again. (You can answer **NO** to the first question and **YES** to the second. )

It will then re-populate the right-click menu of a table (*.vpx) file, showing:

 **"B2S server copy screenres template->backglass deactivated"** 

When selected it will copy the predefined res files to tablename.res next to your table.

Have fun!

**Comment by Loadedweapon** [comment]
Thanks!
