### ISSUE TITLE
Plugin Not Receiving All LED Information

### ISSUE THREAD

**Issue by rdowens11vx** [vpinball/b2s-backglass#7]
What I am doing: building a smart DMD that knows the context of the information and has a configurable attract mode (this is for older ROM tables without a DMD display of their own).  I have a VBS version of this working on 70+ tables and want to move it to C# as an assembly that won't require VBS scripting (or as little as possible). 

I am looking for the best (easy, efficient) way to collect LED / Lamp information from PinMAME.  Building a plugin to B2S seemed a great solution.  But, alas, it's not working properly.

Example stream from the B2S plugin (ingore the long numeric in col 0--it's ticks): 

63797991876144	D 0 -> 102
63797991876145	D 1 -> 111
63797991876146	D 2 -> 6
63797991876146	D 3 -> 111
63797991876147	D 4 -> 111
63797991876148	D 5 -> 63
63797991876148	D 6 -> 102
63797991876149	D 7 -> 111
63797991876150	D 8 -> 6
63797991876151	D 9 -> 111
63797991876152	D 10 -> 111
63797991876152	D 11 -> 63
63797991876153	D 12 -> 102
63797991876154	D 13 -> 111
63797991876155	D 14 -> 6
63797991876156	D 15 -> 111
63797991876157	D 16 -> 111
63797991876158	D 17 -> 63
63797991876159	D 18 -> 102
63797991876160	D 19 -> 111
63797991876161	D 20 -> 6
63797991876162	D 21 -> 111
63797991876163	D 22 -> 111
63797991876164	D 23 -> 63
63797991876165	D 0 -> 0
63797991876704	D 4 -> 63
63797991876705	D 5 -> 63
63797991876706	D 10 -> 63
63797991876707	D 11 -> 63
63797991876708	D 16 -> 63
63797991876709	D 17 -> 63
63797991876710	D 22 -> 63
63797991876711	D 23 -> 63
63797991876712	D 0 -> 0
63797991878629	D 4 -> 63
63797991878630	D 5 -> 63
63797991878631	D 10 -> 63
63797991878632	D 11 -> 63
63797991878633	D 16 -> 63
63797991878634	D 17 -> 63
63797991878635	D 22 -> 63
63797991878636	D 23 -> 63
63797991878637	D 0 -> 0

NOTE that ONLY byte 0 ever gets a "Clear the digit" value (0).  None of the other LEDs ever get a clear / blank value.

Example stream (captured in VPX using a modification of the table script).

LED	4	63
LED	5	63
LED	10	63
LED	11	63
LED	16	63
LED	17	63
LED	22	63
LED	23	63
LED	24	63
LED	25	63
LED	27	63
LED	4	0
LED	5	0
LED	10	0
LED	11	0
LED	16	0
LED	17	0
LED	22	0
LED	23	0
LED	1	111
LED	2	6
LED	3	111
LED	4	111
LED	5	63
LED	7	111
LED	8	6
LED	9	111
LED	10	111
LED	11	63
LED	13	111
LED	14	6
LED	15	111
LED	16	111
LED	17	63
LED	18	102
LED	19	111
LED	20	6
LED	21	111
LED	22	111
LED	23	63
LED	0	102
LED	6	102
LED	12	102
LED	0	0
LED	1	0
LED	2	0
LED	3	0
LED	4	0
LED	5	0
LED	6	0
LED	7	0
LED	8	0
LED	9	0
LED	10	0
LED	11	0
LED	12	0
LED	13	0
LED	14	0
LED	15	0
LED	16	0
LED	17	0
LED	18	0

Byte 0 values map to " " which clears the digit.  This does happen as seem from the table script, but B2S is filtering them out in the plugin data!
 
These samples are from an attract mode where the LEDs are alternating between 00 player scores and a high score.

Without the blanking value, there is no way I can use B2S Plugin as a data source.  I am hoping this can be fixed.  If not, I'd love the help from someone that can tell me how to get the data stream from PinMAME or dmdDevice.dll--I've spent hours looking for documentation and browsing source.  Still not clear on the architecture of how all the peices fit together or where I can connect into the systems.

Thank you!

**Comment by rdowens11vx** [comment]
This issue will be resolved with the suggestion / pull request I made for PluginList.vb.

**Comment by toxieainc** [comment]
Closing then, thanks a lot!
