### ISSUE TITLE
Illumination frames blocked and enlarged on some b2s files

### ISSUE THREAD

**Issue by ivo71** [vpinball/b2s-backglass#74]
Hi,
Some b2s files don't show the illumination frames properly.
For example the Jumanji b2s. Also quite a few of the Starlion b2s have the same problem.
I don't know if this is a design fault, a fault in my system or a bug?
I have added a video to show the problem.
I am using b2s server version 2.1 with the most recent updates on vpx and all other files.
System: Windows 10 pro with Ryzen5800x3D, Geforce 1080ti, 2-screen setup with b2s on 1080p screen and playfield on oled c3 4k.
If you have any idea how to solve this, any help would be much appreciated.
Kindest regards,
[Ivo.]([url](
https://github.com/vpinball/b2s-backglass/assets/40582364/83a0f647-e70b-4e82-bc4d-47c35b0f94aa
))

**Comment by ivo71** [comment]
[Jumanji (Mod 2023) 1.2.zip](https://github.com/vpinball/b2s-backglass/files/13572910/Jumanji.Mod.2023.1.2.zip)
I have added the b2s file, in case that is helpful for you.

**Comment by JockeJarre** [comment]
Hi ivo71, does it work for you now?

**Comment by ivo71** [comment]
Yes, don't know why, but it is okay now. Therefore I closed it.


-------- Original message --------
From: Jarr3 ***@***.***>
Date: 12/01/24 18:55 (GMT+12:00)
To: vpinball/b2s-backglass ***@***.***>
Cc: ivo71 ***@***.***>, State change ***@***.***>
Subject: Re: [vpinball/b2s-backglass] Illumination frames blocked and enlarged on some b2s files (Issue #74)


Hi ivo71, does it work for you now?

**Comment by JockeJarre** [comment]
Which version did it start to work? The latest? (Where you had the admin problem)

**Comment by ivo71** [comment]
2.0.1 release works fine. Before that, when I had the problem I was most likely on 2.0b, unless the date I posted the problem was before 2.0x was available on github.


-------- Original message --------
From: Jarr3 ***@***.***>
Date: 12/01/24 20:09 (GMT+12:00)
To: vpinball/b2s-backglass ***@***.***>
Cc: ivo71 ***@***.***>, State change ***@***.***>
Subject: Re: [vpinball/b2s-backglass] Illumination frames blocked and enlarged on some b2s files (Issue #74)


Which version did it start to work? The latest? (Where you had the admin problem)

**Comment by ivo71** [comment]
I'm still having the admin problem with the 2.1.1 versions as you know, therefore I'm currently using the release 2.1.0 version.


-------- Original message --------
From: Jarr3 ***@***.***>
Date: 12/01/24 20:09 (GMT+12:00)
To: vpinball/b2s-backglass ***@***.***>
Cc: ivo71 ***@***.***>, State change ***@***.***>
Subject: Re: [vpinball/b2s-backglass] Illumination frames blocked and enlarged on some b2s files (Issue #74)


Which version did it start to work? The latest? (Where you had the admin problem)
