### ISSUE TITLE
Backglass dynamic dim mode.

### ISSUE THREAD

**Issue by lukpcn** [vpinball/b2s-backglass#78]
Would it be possible to make a feature, that like modern stern machines dims baclglass down to specified % when game starts and undims when in attract mode?
This would be nice to lower backglass reflection on the playfield and glass.

**Comment by JockeJarre** [comment]
I have no clue how that could be made though. You are invited to make a proposal.

**Comment by lukpcn** [comment]
I was thinking about that:
if backglass can react to some events so it can flash and do some things maybe it can also react to: Start Game (when we press start button) and end game (GameOver).
and b2s-backglass will have additional layer on top of everything (a black image) that normally will be fully transparent (Opacity 0%) but when player starts to play it changes opacity to let's say 70% (configurable, dimming the whole backglass) and when game over event happens then it get's back to original 0% opacity.

**Comment by JockeJarre** [comment]
What about this:  there is a tool from nirsoft called [controlmymonitor](https://www.nirsoft.net/utils/control_my_monitor.html) which can be controlled from scripts. So you can amend the B2SInit script to reduce the brightness (and tons of other parameters) depending on the time of the day.

It is mentioned on the website it only works with Hardware that supports DDC/CI.

**Comment by JockeJarre** [comment]
Sorry, nothing will happen here
