### ISSUE TITLE
Request to turn off backglass in b2s settings

### ISSUE THREAD

**Issue by sakurarozu** [vpinball/b2s-backglass#80]
I would like to ask if we can have a option to turn off the backglass or make it hidden for pup packs but would like to keep the full dmd image.

Thank you

**Comment by Spacegoogie** [comment]
I can to write the same thing lol.

**Comment by JockeJarre** [comment]
As a workaround, it is still possible to create a screenres file and set the position of the backglass outside of the screen.

**Comment by Spacegoogie** [comment]
Why not use a transparent PNG file?

**Comment by Spacegoogie** [comment]
> Why not use a transparent PNG file?

wait....that might not work.

**Comment by JockeJarre** [comment]
After some thoughts on this issue, I wonder how fast the forums will be flooded with questions how to open the settings without a active backglass.
I have now add a requester showing when you try to save the settings with a hidden backglass:

![image](https://github.com/vpinball/b2s-backglass/assets/12571104/7d2703d5-ce42-4035-8b1e-c3241681a268)

We'll see if it will help with a requester like this... who want to bet?

**Comment by sakurarozu** [comment]
That would help at least people won't be lost and ask where is my settings.

**Comment by sakurarozu** [comment]
Now will it be for all tables or specfic tables. Say for example I want terminator 2 backglass hidden since I have a pup will it be just for t2 or everyone?

**Comment by JockeJarre** [comment]
> Now will it be for all tables or specfic tables. Say for example I want terminator 2 backglass hidden since I have a pup will it be just for t2 or everyone?

It is a setting per table, so the table you save with hidden backglass will have it's backglass not shown. You can still get settings opened on the background or b2s-dmd using right click though.

Can you please test the build and then close the issue?

**Comment by Ltek** [comment]
In what cases / tables is this useful?  If you are using a PUP, you can use Pinup Popper to set a backglass, FullDMD, topper, etc. I'm not clear on when a B2S 'just for DMD' is useful?

**Comment by JockeJarre** [comment]
I assume they want to use the possibility to mix the background feature of B2S.Server, but other than that, I have no idea.
But maybe @sakurarozu and @Spacegoogie can chip in?

**Comment by sakurarozu** [comment]
Basically, say for example I like a full dmd that hauntfreaks made but I have a pup pack back ground. I want to keep the dmd but turn off the backglass part so my pup pack can run. Hope that makes senseOn Jun 29, 2024 4:46 AM, Jarr3 ***@***.***> wrote:
I assume they want to use the possibility to mix the background feature of B2S.Server, but other than that, I have no idea.
But maybe @sakurarozu and @Spacegoogie can chip in?

**Comment by Ltek** [comment]
@sakurarozu I understand the idea though I've never seen a situation in real life that needs this. When using Popper, just use a DMD also from Popper. B2S intent is to reproduce an authentic and/or "classic" Backglasses (only small % have DMD builtin).  

What I proposed (and Jarr said 'no') was to have B2Sserver start/stop videos so that people who wanted a video (like an attract video) could run that instead of a FullDMD or a Backglass... and they'd not need Popper (many do not use Popper at all)... https://github.com/vpinball/b2s-backglass/issues/105

**Comment by sakurarozu** [comment]
Well it's more for me since I'm picky, what if I don't want to use a dmd from popper. What if I want to use the dmd from hauntfreaks designs but I don't need the backglass. One way was to do a whole new screen res setup and save it under the table name but that is too much work and this would be on the fly all you need to do is reload the table and no more top image just the dmd remains. I like it and I use it when dmd from poppers aren't that good and I prefer a non video one. On Jul 4, 2024 10:27 AM, Ltek ***@***.***> wrote:
@sakurarozu I understand the idea though I've never seen a situation in real life that needs this. When using Popper, just use a DMD also from Popper. B2S intent is to reproduce an authentic and/or "classic" Backglasses (only small % have DMD builtin).
What I proposed (and Jarr said 'no') was to have B2Sserver start/stop videos so that people who wanted a video (like an attract video) could run that instead of a FullDMD or a Backglass... and they'd not need Popper (many do not use Popper at all)... #105

**Comment by Ltek** [comment]
agree for sure that more flexibility is better than less 👯 and what I suggested in my posted issue would run videos in the Backglass and support the exact use case you are asking for... without the need for popper at all. (play DMD from B2S file, and a video on the backglass)

**Comment by JockeJarre** [comment]
> Well it's more for me since I'm picky, what if I don't want to use a dmd from popper. What if I want to use the dmd from hauntfreaks designs but I don't need the backglass. One way was to do a whole new screen res setup and save it under the table name but that is too much work 

Well, it seems you haven't tried the ScreenResTemplates feature, you just stick this one "whole new screen res setup.res" file into the ScreenResTemplates folder and re-register the context menu (second question in B2SBackglassServerRegisterApp).
Then when you have one Backglass you want this kind of, you right click the backglass file and choose "whole new screen res setup" and it will automatically copy the file into tableName.res

This can be used for many other settings like borders and such. See [RightMouseClick-Context-Menu](https://github.com/vpinball/b2s-backglass/wiki/RightMouseClick-Context-Menu)
