### ISSUE TITLE
DisableFuzzyMatching is true however it behaves as if it is set as false

### ISSUE THREAD

**Issue by Nicolainuke** [vpinball/b2s-backglass#85]
I have an issue where DisableFuzzyMatching is true in the global settings in the B2STableSettings.xml, however it behaves as if it is set as false.
Example; when I launch "Attack From Mars (Bally 1995)" the directb2s file for "Attack and Revenge from Mars (Bally 1999)" is displayed. My B2STableSettings.xml file only has global settings, no table specific settings at all. Also, my "Attack From Mars (Bally 1995)"  table uses the puppack, so no "Attack From Mars (Bally 1995).directb2s" file exists.
I added a global setting for FormToFront and FormToBack in the B2STableSettings.xml file, but I believe the problem existed before this change.

![Screenshot 2024-03-10 140338](https://github.com/vpinball/b2s-backglass/assets/94946962/fcf05ac3-5e0d-4320-a073-f0807e991330)
![Screenshot 2024-03-10 140313](https://github.com/vpinball/b2s-backglass/assets/94946962/b0c0bd2d-f04f-4e46-8210-df7c48f206ec)

**Comment by JockeJarre** [comment]
please try to use DefaultStartMode = 2 (EXE) and from here you have access to most of the newer features.

There is a reason it says in the bottom:   * all settings in Italic is only available when tun in EXE mode!
