### ISSUE TITLE
Set "Start As EXE" as Default

### ISSUE THREAD

**Issue by syd711** [vpinball/b2s-backglass#86]
Is there a way to enable the "Start As Exe" by default?

I can set this setting in the B2STableSettings.xml "<StartAsEXE>1</StartAsEXE>" for every table, but when I move it to the global setting sections, it does not have an effect. I didn't find find anything in the Wiki, or maybe missed this.

**Comment by JockeJarre** [comment]
Check in the settings, there is a "default mode" 

See https://github.com/vpinball/b2s-backglass/wiki/Settings

**Comment by syd711** [comment]
Must have been blind...

Thank you for the quick response and for your work!
