### ISSUE TITLE
three state "Form to Top" setting

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/b2s-backglass#9]
The "Form to Top" setting should get another way to move the background to the back as well. When both "Form to Back" and "Form to Top" is turned off it should work 100% as in the earlier releases. When "Form to Back" is turned on it has precedence.

_Originally posted by @JockeJarre in https://github.com/vpinball/b2s-backglass/issues/3#issuecomment-1247903690_

**Comment by wiesshund** [comment]
you have a test build?

**Comment by JockeJarre** [comment]
yes, it is still in my fork

https://github.com/JockeJarre/b2s-backglass/actions/runs/3123621442

**Comment by wiesshund** [comment]
@JockeJarre 
Oh, that works perfect

I mean the dmd's and alphas dont even dive behind the backglass anymore when you touch it.
used to be, if you engaged the bs2 like right clicking it, it yanked it over everything and it stayed there till you restarted it.

Yea this seems good.

And if freezy could add either non aspect sizing of alphas or better yet, allow adjusting the padding between digits
you would have exactly what you are looking for.

**Comment by JockeJarre** [comment]
Cool, thanks for testing, will push it to the official repo tonight
