### ISSUE TITLE
Improve Fuzzy Matching to not use the DOS short names

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/b2s-backglass#96]
Improve Fuzzy Matching to not use the DOS short names as "Fuzzy Matching".

Instead, use the table name with full name, manufacturer and year (the last two in parentheses) as the short name.

This way a table like "Blood Machines (VPW 2022) V1.21.vpx" would find a "Blood Machines (VPW 2022) mod.directb2s" and not "Blood China" anymore.
It will still be optional, and might even be possible to choose one in case more then one exists.

**Comment by stevejones72** [comment]
I started to write some code for this:

The basic premise goes something like:
Use a regex to check the tablename is in the format something like {Title}({Manufacturer} {Year})
Then search for all B2S Files that have Title,
Search that subset with the addition of Manufacturer
Search that subset for Year
Use the first one of the last subset to contain at least one element.

Once you get down to the postfix of versions etc.. it all gets a bit messy as there are no standards on that :)

**Comment by JockeJarre** [comment]
The current solution just cuts at DOS 8 chars... so anything is better then that...
I was thinking to cut just after {Title}({Manufacturer} {Year}) and return every file which fit this.

**Comment by JockeJarre** [comment]
It is now just cutting after the first right parenthesis and finds the files.
E.g. "Blood Machines (VPW 2022) V 2" will search any file like "Blood Machines (VPW 2022)*.directb2s" and show them as options in the settings.
If it finds "Blood Machines (VPW 2022) V 2.directb2s" or "Blood Machines (VPW 2022).directb2s" it will be directly used.
