### ISSUE TITLE
B2S Server v2.1.1 download detected with theTrojan Wacatac.B!ml

### ISSUE THREAD

**Issue by layby2k** [vpinball/b2s-backglass#97]
The latest version v2.1.1 zip archive is detected by both Chrome and Windows Defender as having the Wacatac.B!ml trojan.  Version 2.1.0 is fine.

![image](https://github.com/vpinball/b2s-backglass/assets/147611407/55d67a28-dc42-43ed-9033-f91d4bf858c3)

![image](https://github.com/vpinball/b2s-backglass/assets/147611407/4ce2360e-239d-4832-883b-3483f33616e6)

**Comment by JockeJarre** [comment]
I have regenerated 2.1.1 and now it should be "clean". For sure a virus scanner false negative.
Thanks for the finding.

**Comment by layby2k** [comment]
No worries, tried to download the new B2S Server v2.1.1 RC2 release but it too is also detected by both Google Chrome and Defender.  Very Strange

**Comment by JockeJarre** [comment]
I have now reported to Max "Secure" and received the same answer as the examples I found on the net.
Then I also reported directly to VirusTotal.com this:

> Max "Secure" is the only out of 60 Virus Scanners which reports our open source software as infected.
> The file can be found here https://github.com/vpinball/b2s-backglass/releases/tag/b2s-backglass-bfab24d
> Here is the report:  https://www.virustotal.com/gui/file/8044d85be010a849a4651d654d198c7e2c96105d0a8fbab89c813088dd46b8de
> 
> What can I do about it?
> 
> Kind regards
> 

We'll see what and IF we get an answer

**Comment by JockeJarre** [comment]
A few days later. I have contacted both Max "Secure" and virustotal. Max "Secure" has yet to get back to me, whereas virustotal responded promptly and professionally.

**Comment by JockeJarre** [comment]
Max "Secure" have finally changed their mind:

![image](https://github.com/vpinball/b2s-backglass/assets/12571104/309211ac-09cb-4000-a57c-cc63e51d38a3)
