### ISSUE TITLE
Communication between server and COM object does not support PWM GI

### ISSUE THREAD

**Issue by vbousquet** [vpinball/b2s-backglass#99]
The issue is clearly described here: https://github.com/vpinball/pinmame/issues/267

The problem seems to be in the communication through Windows registry see:
- https://github.com/vpinball/b2s-backglass/blob/d5b275e6e3f4edbf1f109c127069f891191497b8/b2sbackglassserverexe/b2sbackglassserverexe/Server.vb#L667 => GI state is read as a single char
- https://github.com/vpinball/b2s-backglass/blob/d5b275e6e3f4edbf1f109c127069f891191497b8/b2sbackglassserver/b2sbackglassserver/Server.vb#L1260 => GI state is inserted as is, which can be more than one char when using PWM

The solution would be either to at least clamp the value to 9 or to go for a clean full support (more complicated though).

**Comment by JockeJarre** [comment]
Works!
